version: '3'
services:

  # Zookeeper Service
  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    container_name: zookeeper-server
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  # Kafka Service
  kafka:
    image: 'bitnami/kafka:3.4'
    container_name: kafka-broker
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  kafka_data:
    driver: local
  zookeeper_data:
    driver: local
